import crypto from 'node:crypto';
import path from 'node:path';
import express from 'express';
import { config, ROOT } from './config.js';
import * as db from './db.js';
import { generateCode, signCode, verifySignature, parseToken, normaliseCode, tokenUrl } from './codes.js';
import { qrMatrix, qrPngBuffer, qrSvg } from './qr.js';
import {
  sessionMiddleware, requireAuth, checkPassword, issueToken,
  setSessionCookie, clearSessionCookie, rateLimiter,
} from './auth.js';

const PUBLIC_DIR = path.join(ROOT, 'public');
const page = (name) => (_req, res) => res.sendFile(path.join(PUBLIC_DIR, name));

/** Everything the browser needs to draw one coupon. */
function couponPayload(row) {
  const url = tokenUrl(row.code, row.sig);
  return {
    code: row.code,
    sig: row.sig,
    amount: row.amount,
    status: row.status,
    batchRef: row.batch_ref,
    createdAt: row.created_at,
    expiresAt: row.expires_at,
    usedAt: row.used_at,
    usedBy: row.used_by,
    url,
    qr: qrMatrix(url),
  };
}

/** CSV cell: quote anything that could break the column layout. */
function csvCell(value) {
  const text = String(value ?? '');
  return /[",\n\r]/.test(text) ? '"' + text.replace(/"/g, '""') + '"' : text;
}

const EXPORT_TIME = new Intl.DateTimeFormat('en-CA', {
  timeZone: config.timezone, year: 'numeric', month: '2-digit', day: '2-digit',
  hour: '2-digit', minute: '2-digit', hour12: false,
});

/** "2026-09-07 15:42" in the campaign's own time zone — a date Sheets understands. */
function localTime(iso) {
  if (!iso) return '';
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return '';
  const parts = Object.fromEntries(EXPORT_TIME.formatToParts(date).map((part) => [part.type, part.value]));
  return `${parts.year}-${parts.month}-${parts.day} ${parts.hour}:${parts.minute}`;
}

const STATUS_LABEL = { active: 'صالح', used: 'مستخدم', void: 'ملغى' };

function timingSafeEquals(a, b) {
  const left = crypto.createHash('sha256').update(String(a)).digest();
  const right = crypto.createHash('sha256').update(String(b)).digest();
  return crypto.timingSafeEqual(left, right);
}

function isExpired(row) {
  return Boolean(row?.expires_at) && new Date(row.expires_at).getTime() < Date.now();
}

/**
 * The heart of the verifier: is this coupon one of ours, and can it be used?
 * `signatureOk` answers "was it generated by this site"; the database answers
 * "has it already been used".
 */
function assess(code, sig) {
  const row = db.getCoupon(code);
  const signatureOk = sig ? verifySignature(code, sig) : null;

  if (sig && signatureOk === false) return { result: 'forged', signatureOk: false, coupon: row ? couponPayload(row) : null };
  if (!row) return { result: 'unknown', signatureOk, coupon: null };
  if (row.status === 'void') return { result: 'void', signatureOk, coupon: couponPayload(row) };
  if (row.status === 'used') return { result: 'used', signatureOk, coupon: couponPayload(row) };
  if (isExpired(row)) return { result: 'expired', signatureOk, coupon: couponPayload(row) };
  return { result: 'valid', signatureOk, coupon: couponPayload(row) };
}

export function createApp() {
  const app = express();
  if (config.trustProxy) app.set('trust proxy', true);
  app.disable('x-powered-by');
  app.use(express.json({ limit: '256kb' }));
  app.use(express.urlencoded({ extended: false }));
  app.use(sessionMiddleware);

  app.use((_req, res, next) => {
    res.set('X-Content-Type-Options', 'nosniff');
    res.set('Referrer-Policy', 'same-origin');
    next();
  });

  // ---------------------------------------------------------------- pages ---
  app.get('/login', page('login.html'));
  app.get('/verify', page('verify.html'));
  // What a phone camera opens after scanning; the page reads the token itself.
  app.get('/v/:token', (_req, res) => res.sendFile(path.join(PUBLIC_DIR, 'verify.html')));
  app.get('/', requireAuth, page('index.html'));
  app.get('/coupons', requireAuth, page('coupons.html'));
  app.get('/print', requireAuth, page('print.html'));

  app.use(express.static(PUBLIC_DIR, { index: false, maxAge: '1h' }));
  app.use('/vendor', express.static(path.join(ROOT, 'node_modules', 'jsqr', 'dist'), { maxAge: '1d' }));

  // --------------------------------------------------------------- session ---
  app.post('/api/login', rateLimiter({ windowMs: 60_000, max: 10 }), (req, res) => {
    if (!checkPassword(req.body?.password)) {
      return res.status(401).json({ error: 'bad_password', message: 'كلمة المرور غير صحيحة' });
    }
    setSessionCookie(res, issueToken('staff'));
    res.json({ ok: true });
  });

  app.post('/api/logout', (_req, res) => { clearSessionCookie(res); res.json({ ok: true }); });

  app.get('/api/session', (req, res) => res.json({
    authenticated: Boolean(req.session),
    user: req.session?.user ?? null,
    prefix: config.prefix,
    defaultAmount: config.defaultAmount,
    publicUrl: config.publicUrl,
  }));

  // ---------------------------------------------------------------- verify ---
  // Public on purpose: a pilgrim can confirm a coupon is genuine before paying.
  // Anonymous callers get the verdict only — never the signature, the QR or the
  // verify URL, so a leaked code can never be turned into a working coupon.
  app.get('/api/verify', rateLimiter({ windowMs: 60_000, max: 60 }), (req, res) => {
    const parsed = parseToken(String(req.query.token || req.query.code || ''));
    if (!parsed) {
      return res.status(400).json({ result: 'malformed', message: 'صيغة الكود غير صحيحة' });
    }
    const verdict = assess(parsed.code, parsed.sig);
    db.logScan({ code: parsed.code, result: verdict.result, ip: req.ip || '', actor: req.session?.user || 'public' });

    let coupon = verdict.coupon;
    if (verdict.result === 'forged') coupon = null;
    else if (coupon && !req.session) {
      const { sig, url, qr, usedBy, ...safe } = coupon;
      coupon = safe;
    }
    res.json({
      ...verdict,
      coupon,
      code: parsed.code,
      canRedeem: Boolean(req.session) && verdict.result === 'valid',
    });
  });

  // ---------------------------------------------------------------- batches ---
  app.post('/api/batches', requireAuth, (req, res) => {
    const quantity = Number(req.body?.quantity);
    if (!Number.isInteger(quantity) || quantity < 1 || quantity > config.maxBatchSize) {
      return res.status(400).json({ error: 'bad_quantity', message: `العدد يجب أن يكون بين 1 و ${config.maxBatchSize}` });
    }
    const amount = String(req.body?.amount ?? config.defaultAmount).trim().slice(0, 12) || config.defaultAmount;
    const note = String(req.body?.note ?? '').trim().slice(0, 200);
    let expiresAt = null;
    if (req.body?.expiresAt) {
      const date = new Date(req.body.expiresAt);
      if (Number.isNaN(date.getTime())) return res.status(400).json({ error: 'bad_date', message: 'تاريخ الانتهاء غير صحيح' });
      expiresAt = date.toISOString();
    }

    const { batch, coupons } = db.createBatch({
      quantity, amount, note, expiresAt,
      createdBy: req.session.user,
      mint: () => { const code = generateCode(); return { code, sig: signCode(code) }; },
    });
    res.status(201).json({
      batch,
      coupons: coupons.map((c) => couponPayload({ ...c, batch_ref: batch.ref })),
    });
  });

  app.get('/api/batches', requireAuth, (_req, res) => res.json({ batches: db.listBatches() }));

  app.get('/api/batches/:ref', requireAuth, (req, res) => {
    const batch = db.getBatch(req.params.ref);
    if (!batch) return res.status(404).json({ error: 'not_found', message: 'الدفعة غير موجودة' });
    const { rows } = db.listCoupons({ batchRef: batch.ref, limit: config.maxBatchSize });
    res.json({ batch, coupons: rows.map(couponPayload) });
  });

  app.get('/api/batches/:ref/export.csv', requireAuth, (req, res) => {
    const batch = db.getBatch(req.params.ref);
    if (!batch) return res.status(404).json({ error: 'not_found' });
    const { rows } = db.listCoupons({ batchRef: batch.ref, limit: config.maxBatchSize });
    const header = 'code,signature,amount,status,created_at,used_at,verify_url';
    const body = rows.map((r) => [
      r.code, r.sig, r.amount, r.status, r.created_at, r.used_at ?? '', tokenUrl(r.code, r.sig),
    ].join(',')).join('\n');
    res.set('Content-Type', 'text/csv; charset=utf-8');
    res.set('Content-Disposition', `attachment; filename="${batch.ref}.csv"`);
    res.send('﻿' + header + '\n' + body + '\n');
  });

  // ---------------------------------------------------------------- coupons ---
  app.get('/api/coupons', requireAuth, (req, res) => {
    const limit = Math.min(Number(req.query.limit) || 50, 500);
    const offset = Math.max(Number(req.query.offset) || 0, 0);
    const { rows, total } = db.listCoupons({
      status: ['active', 'used', 'void'].includes(req.query.status) ? req.query.status : '',
      batchRef: String(req.query.batch || ''),
      search: String(req.query.q || '').replace(/[^0-9A-Za-z-]/g, ''),
      limit, offset,
    });
    res.json({ coupons: rows.map(couponPayload), total, limit, offset });
  });

  app.get('/api/stats', requireAuth, (_req, res) => res.json(db.stats()));
  app.get('/api/scans', requireAuth, (_req, res) => res.json({ scans: db.recentScans(40) }));

  /** Resolves :code for every coupon route below. */
  function withCoupon(req, res, next) {
    const code = normaliseCode(req.params.code);
    const row = code && db.getCoupon(code);
    if (!row) return res.status(404).json({ error: 'not_found', message: 'الكوبون غير موجود' });
    req.coupon = row;
    next();
  }

  app.get('/api/coupons/:code', requireAuth, withCoupon, (req, res) => res.json({
    coupon: couponPayload(req.coupon),
    scans: db.listScans(req.coupon.code),
  }));

  app.get('/api/coupons/:code/qr.png', requireAuth, withCoupon, async (req, res) => {
    const width = Math.min(Math.max(Number(req.query.size) || 512, 128), 2048);
    res.type('png').send(await qrPngBuffer(tokenUrl(req.coupon.code, req.coupon.sig), width));
  });

  app.get('/api/coupons/:code/qr.svg', requireAuth, withCoupon, async (req, res) => {
    res.type('svg').send(await qrSvg(tokenUrl(req.coupon.code, req.coupon.sig)));
  });

  app.post('/api/coupons/:code/redeem', requireAuth, withCoupon, (req, res) => {
    const code = req.coupon.code;
    if (isExpired(req.coupon)) {
      db.logScan({ code, result: 'expired', action: 'redeem', ip: req.ip || '', actor: req.session.user });
      return res.status(409).json({ error: 'expired', message: 'انتهت صلاحية الكوبون', coupon: couponPayload(db.getCoupon(code)) });
    }
    const outcome = db.redeemCoupon(code, req.session.user);
    db.logScan({ code, result: outcome.ok ? 'redeemed' : outcome.reason, action: 'redeem', ip: req.ip || '', actor: req.session.user });
    if (!outcome.ok) {
      const messages = { already_used: 'الكوبون مستخدم مسبقاً', void: 'الكوبون ملغى', unknown: 'الكوبون غير موجود' };
      return res.status(409).json({ error: outcome.reason, message: messages[outcome.reason] ?? 'تعذّر التنفيذ',
        coupon: outcome.coupon ? couponPayload(db.getCoupon(code)) : null });
    }
    res.json({ ok: true, coupon: couponPayload(outcome.coupon) });
  });

  app.post('/api/coupons/:code/restore', requireAuth, withCoupon, (req, res) => {
    const outcome = db.restoreCoupon(req.coupon.code);
    db.logScan({ code: req.coupon.code, result: 'restored', action: 'restore', ip: req.ip || '', actor: req.session.user });
    res.json({ ok: outcome.ok, coupon: outcome.coupon ? couponPayload(outcome.coupon) : null });
  });

  app.post('/api/coupons/:code/void', requireAuth, withCoupon, (req, res) => {
    const voided = req.body?.void !== false;
    const outcome = db.setVoid(req.coupon.code, voided);
    if (!outcome.ok) return res.status(409).json({ error: outcome.reason, message: 'الكوبون مستخدم مسبقاً' });
    db.logScan({ code: req.coupon.code, result: voided ? 'voided' : 'unvoided', action: 'void', ip: req.ip || '', actor: req.session.user });
    res.json({ ok: true, coupon: couponPayload(outcome.coupon) });
  });

  // ------------------------------------------------------- Google Sheets ---
  // A read-only, key-protected CSV so a spreadsheet can pull the register with
  // =IMPORTDATA(). Signatures and verify links are deliberately left out: the
  // link is a shared secret, and a leaked one must not yield usable coupons.
  app.get('/api/export.csv', rateLimiter({ windowMs: 60_000, max: 30 }), (req, res) => {
    if (!config.exportEnabled) return res.status(404).json({ error: 'not_found' });
    const key = String(req.query.key || '');
    if (!key || !timingSafeEquals(key, config.exportKey)) {
      return res.status(403).json({ error: 'forbidden', message: 'مفتاح التصدير غير صحيح' });
    }
    const batchRef = String(req.query.batch || '');
    const { rows } = db.listCoupons({ batchRef, limit: 5000 });
    const header = ['الكود', 'الدفعة', 'القيمة', 'الحالة', 'تاريخ التوليد', 'تاريخ الاستخدام', 'ينتهي في'];
    const body = rows.map((row) => [
      row.code,
      row.batch_ref,
      row.amount,
      STATUS_LABEL[row.status] ?? row.status,
      localTime(row.created_at),
      localTime(row.used_at),
      localTime(row.expires_at),
    ].map(csvCell).join(','));
    res.set('Content-Type', 'text/csv; charset=utf-8');
    res.set('Cache-Control', 'no-store');
    res.send([header.join(','), ...body].join('\n') + '\n');   // no BOM: Sheets reads UTF-8
  });

  app.get('/api/export-link', requireAuth, (_req, res) => {
    if (!config.exportEnabled) return res.json({ enabled: false });
    const url = `${config.publicUrl}/api/export.csv?key=${encodeURIComponent(config.exportKey)}`;
    res.json({ enabled: true, url, formula: `=IMPORTDATA("${url}")`, timezone: config.timezone });
  });

  // ------------------------------------------------------------------ misc ---
  app.get('/healthz', (_req, res) => res.json({ ok: true }));

  app.use((req, res) => {
    if (req.path.startsWith('/api/')) return res.status(404).json({ error: 'not_found' });
    res.status(404).sendFile(path.join(PUBLIC_DIR, '404.html'));
  });

  app.use((err, _req, res, _next) => {
    console.error('[error]', err);
    res.status(500).json({ error: 'server_error', message: 'حدث خطأ في الخادم' });
  });

  return app;
}
